# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Basic site settings ###################################################

title: Giorgio Carbone
email: carbone.giorgio4@gmail.com
author: Giorgio Carbone
description: >- # this means ignore newlines
  Giorgio Carbone is a Master's Degree student in Data Science at University of Milano-Bicocca. 
  He has a scientific background having earned a Bachelor's Degree in Chemical Sciences and Technologies. 
  He is passionate about AI, statistics, science, technology and music.

baseurl: ""
url: "https://giocoal.github.io/giorgiocarbone.github.com/"

# Jekyll settings #######################################################

# this tells jekyll to include the content of the _pages
# folder when generating the static site
include:
  - _pages

# options for SASS (compiled CSS)
sass:
  # source folder
  sass_dir: _sass
  # when compiling, minimize size
  style: compressed

### ! these cannot be changed for Github pages ! ###

# index for related posts
lsi: false
# disable custom plugins
safe: true
# markdown conversion
markdown: kramdown
# highlighting for text and code
highlighter: rouge
# build only pages that changed
incremental: false

### ! these can be changed ! ###

# show excerpts from posts on the news page
show_excerpts: true

# Jekyll plugins go here
plugins:
  # generate a <head> tag for SEO automatically
  - jekyll-seo-tag
  # generates an rss feed from posts and news
  - jekyll-feed
  
# Custom settings #######################################################

# social/analytics variables
logo: "/assets/images/me.jpg"
#google_analytics: UA-56200536-1
linkedin_username: giorgiocarbone
#twitter_username: iacomip
github_username:  giocoal
#google_scholar: 4_E8rqcAAAAJ
#orc_id: 0000-0001-5477-1503

# Nav
navigation:
  - item: "About"
    link: "/about/"
  - item: "Research"
    link: "/academic/"
  - item: "Resume"
    link: "assets/Carbone_Giorgio_CV.pdf"
  - item: "Software"
    link: "/software/"
  - item: "Thoughts"
    link: "/posts/"
